[package]
name = "day09"
version = "0.1.0"
authors = ["Nicholas Sizer <senseibaka@senseibaka.com>"]
edition = "2018"

[dependencies]
common = { path = "../../common" }
intcode = { path = "../intcode" }
